name: build

on:
  push:
    branches:
      - master
  release:
    types: [published]
#
jobs:
  build_linux:
    name: build linux kernel
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
